"""
models.py — Pydantic v2 Data Contracts for Project GEMA.

Every layer of the pipeline communicates through these models.
No raw dicts cross module boundaries — every piece of data is validated
at the entry point and typed throughout its lifetime.

Architecture role:
    NLP Engine  → produces SearchConfig
    Scraper     → produces list[JobResult]
    Matcher     → produces list[TieredJob]
    Database    → persists/retrieves SearchVaultEntry
    Integrations→ consume TieredJob to push to Notion/Sheets
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Optional
from pydantic import BaseModel, Field, field_validator, model_validator


# =============================================================================
# NLP Contract — Output of the LLM Engine
# =============================================================================

class SearchConfig(BaseModel):
    """
    The structured output of the NLP engine.
    This is the 'source of truth' contract that all downstream layers consume.

    Generated by: nlp_engine.py
    Consumed by:  scraper.py, matcher.py, database.py (vault)
    """

    target_titles: list[str] = Field(
        ...,
        min_length=1,
        description="Job titles to search for. At least one required.",
        examples=[["Senior SDET", "Automation Engineer", "QA Automation"]],
    )
    must_include: list[str] = Field(
        default_factory=list,
        description="Keywords that MUST appear in title or salary metadata.",
        examples=[["Remote", "100% Remote"]],
    )
    must_exclude: list[str] = Field(
        default_factory=list,
        description="Keywords that disqualify a job if found.",
        examples=[["Contract", "Hybrid", "On-site"]],
    )
    min_salary: Optional[int] = Field(
        default=None,
        ge=0,
        description="Minimum annual salary in USD. None = no filter.",
        examples=[90000],
    )
    target_domains: list[str] = Field(
        default_factory=list,
        description="Job board domains to scrape.",
        examples=[["himalayas.app", "trueup.io"]],
    )

    # God Mode overrides (Vol 1.1 / Vol 1.4)
    custom_xpath: Optional[str] = Field(
        default=None,
        description="God Mode: custom XPath selector for job card title element.",
    )
    custom_css: Optional[str] = Field(
        default=None,
        description="God Mode: custom CSS selector override for job card.",
    )

    @field_validator("target_titles", "must_include", "must_exclude", mode="before")
    @classmethod
    def strip_and_deduplicate(cls, v: list) -> list:
        """Normalize whitespace and remove duplicates while preserving order."""
        seen: set = set()
        result: list = []
        for item in v:
            cleaned = str(item).strip()
            if cleaned and cleaned.lower() not in seen:
                seen.add(cleaned.lower())
                result.append(cleaned)
        return result

    @field_validator("target_domains", mode="before")
    @classmethod
    def normalize_domains(cls, v: list) -> list:
        """Strip protocols and trailing slashes from domain strings."""
        cleaned = []
        for domain in v:
            d = str(domain).strip()
            d = d.replace("https://", "").replace("http://", "").rstrip("/")
            if d:
                cleaned.append(d)
        return cleaned

    @model_validator(mode="after")
    def validate_no_overlap(self) -> SearchConfig:
        """Must-include and must-exclude cannot share keywords."""
        include_lower = {k.lower() for k in self.must_include}
        exclude_lower = {k.lower() for k in self.must_exclude}
        overlap = include_lower & exclude_lower
        if overlap:
            raise ValueError(
                f"Keywords cannot be in both must_include and must_exclude: {overlap}"
            )
        return self


# =============================================================================
# Scraper Output — Raw surface metadata
# =============================================================================

class JobResult(BaseModel):
    """
    Surface metadata extracted by the scraper.
    STRICT RULE: No job description content. Title, company, salary, link only.

    Generated by: scraper.py
    Consumed by:  matcher.py, database.py
    """

    title: str = Field(..., description="Job title as displayed on the listing.")
    company: str = Field(..., description="Company name — fallback key if URL rots.")
    url: str = Field(..., description="Direct link to the job posting.")
    salary_raw: Optional[str] = Field(
        default=None,
        description="Raw salary string as scraped (e.g. '$120k - $150k'). "
                    "None if not published.",
    )
    source_domain: str = Field(..., description="The job board domain this was scraped from.")
    scraped_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of extraction.",
    )

    @field_validator("url", mode="before")
    @classmethod
    def normalize_url(cls, v: str) -> str:
        """Strip trailing slashes and whitespace for consistent hashing."""
        return str(v).strip().rstrip("/")

    @field_validator("title", "company", mode="before")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        return str(v).strip()

    def parse_salary_usd(self) -> Optional[int]:
        """
        Parses salary_raw to an integer USD annual value.
        Returns None if no currency-anchored amount is found.

        TWO STRICTLY ANCHORED PATHS — no standalone digits accepted:

        Path 1  (dollar prefix):
            Requires a literal $ before the number.
            Matches: '$120k', '$90,000', '$120k - $150k', '$85,000/yr'
            Rejects: anything without a leading $

        Path 2  (usd suffix):
            Requires the word 'usd' immediately after the number/k.
            Matches: '120k usd', '85k USD', '90 usd'
            Rejects: '401k match' — no 'usd' follows the k, so no match

        REJECTS: '401k', '401k match', 'equity', 'DOE', 'Competitive'

        GROUP LAYOUT — 4-tuple per match (alternation produces two pairs):
            (dollar_num, dollar_k, usd_num, usd_k)
            Only ONE pair is populated per match; the other pair is empty.

        DIGIT FLOOR — the {2,3} quantifier requires at least 2 leading
        digits, preventing spurious matches on $1 or $5 text fragments.
        Minimum matchable amount: $10.

        Salary ranges ('$120k - $150k') return the minimum value —
        conservative estimate for the salary gate filter.
        """
        if not self.salary_raw:
            return None

        import re
        # Input is lowercased so the usd\b branch matches 'USD', 'usd', 'Usd'.
        # Dollar signs are not affected by lower().
        raw = self.salary_raw.lower()

        matches = re.findall(
            r'(?:\$)\s*(\d{2,3}(?:,\d{3})*(?:\.\d+)?)\s*(k)?'
            r'|'
            r'(\d{2,3}(?:\.\d+)?)\s*(k)?\s*(?:usd\b)',
            raw,
        )
        if not matches:
            return None

        values = []
        for dollar_num, dollar_k, usd_num, usd_k in matches:
            # Determine which alternation arm fired
            num_str = dollar_num if dollar_num else usd_num
            suffix  = (dollar_k  if dollar_num else usd_k).lower()
            if not num_str:
                continue
            try:
                val = float(num_str.replace(",", ""))
                if suffix == "k":
                    val *= 1000
                values.append(int(val))
            except ValueError:
                continue

        return min(values) if values else None


# =============================================================================
# Intelligence Layer — Scored and bucketed job
# =============================================================================

class TieredJob(BaseModel):
    """
    A JobResult enriched with a match score and tier classification.

    Generated by: matcher.py
    Consumed by:  main.py (display), integrations/
    """

    job: JobResult
    match_score: int = Field(
        ...,
        ge=-1,
        le=100,
        description=(
            "0–100 match percentage for scored tiers (Tier 1/2/3). "
            "-1 is the sentinel value for Tier 4 (Manual Review) jobs "
            "that bypass mathematical scoring entirely."
        ),
    )
    tier: str = Field(..., description="'Tier 1', 'Tier 2', or 'Tier 3'.")
    match_reasons: list[str] = Field(
        default_factory=list,
        description="Human-readable list of which criteria matched.",
    )
    miss_reasons: list[str] = Field(
        default_factory=list,
        description="Human-readable list of which criteria did NOT match.",
    )

    @field_validator("tier")
    @classmethod
    def validate_tier(cls, v: str) -> str:
        allowed = {"Tier 1", "Tier 2", "Tier 3", "Tier 4"}
        if v not in allowed:
            raise ValueError(f"tier must be one of {allowed}, got '{v}'")
        return v


# =============================================================================
# Search Vault — Persisted search configurations (Vol 1.3)
# =============================================================================

class SearchVaultEntry(BaseModel):
    """
    A saved search configuration with metadata for the Search Vault.

    Generated by: main.py (on user save)
    Persisted by: database.py (search_vault table)
    """

    vault_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this vault entry.",
    )
    label: str = Field(
        ...,
        description="User-defined label (e.g. 'Senior SDET Remote June 2026').",
    )
    config: SearchConfig
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
    times_used: int = Field(default=0, ge=0)


# =============================================================================
# Scrape Run Session — Tracks a complete scraper execution
# =============================================================================

class ScrapeRunSummary(BaseModel):
    """
    Summary statistics for a completed scraper run.
    Displayed in the Streamlit console and stored for audit.
    """

    run_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    started_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    completed_at: Optional[datetime] = None
    total_urls_found: int = 0
    skipped_seen: int = 0       # Delta Load: already in registry
    skipped_ttl: int = 0        # Delta Load: within TTL window
    new_processed: int = 0
    tier1_count: int = 0
    tier2_count: int = 0
    tier3_count: int = 0
    domains_aborted: list[str] = Field(default_factory=list)  # Circuit breaker
    errors: list[str] = Field(default_factory=list)

    @property
    def duration_seconds(self) -> Optional[float]:
        if self.completed_at:
            return (self.completed_at - self.started_at).total_seconds()
        return None


# =============================================================================
# Extraction Layer — LLM Structured Job Data (The "Shy Principle" contract)
# =============================================================================

class ExtractedJob(BaseModel):
    """
    The output contract for the LLM-based job description extraction engine.

    DESIGN PHILOSOPHY — The Shy Principle:
        Every field defaults to null or an empty list.
        The LLM is forbidden from inferring or guessing. If the data is not
        explicitly stated in the source text, the field must be null.
        A null field is honest. A hallucinated field is a data integrity failure.

    FIELD DECISIONS (all changes from original prompt design documented):

        salary_min / salary_max:
            Split from a single field because job posts almost always state
            ranges ("$90k - $120k"). A single number forces arbitrary choice.
            Both are nullable integers — no string type annotations that would
            cause the LLM to return "null" (string) vs null (JSON).

        remote_region:
            Replaces the original two-boolean (is_remote_global, is_remote_us_only)
            design. Two booleans have an impossible state (both True) and no way
            to express EU-only, Canada-only, or CONFLICT cases.
            Values: "GLOBAL", "US", "EU", "CA", "CONFLICT", null

        location_conflict_detected:
            True when the metadata/title says one thing and the body text says
            another (e.g. "United States" in the dropdown but "open to candidates
            worldwide" in the description). The LLM always trusts body text over
            metadata but surfaces the conflict for human review.

        location_notes:
            Verbatim quote of the conflicting phrase from the source text.
            Never paraphrased — the LLM copies exact words. Null when no conflict.

        required_tech / preferred_tech:
            Split because job posts distinguish "Required: Python, K8s" from
            "Nice to have: Go, Terraform." Merging them means your must_include
            filter treats nice-to-haves as hard requirements.

        experience_min_years / experience_max_years:
            Replaces single years_experience. "3-5 years" is the most common
            format. A single field would silently lose half the data.

        seniority_level:
            Extracted separately from title. Saves the matcher from regex
            matching "Staff", "Senior", "Principal", "Lead" in title strings.

        employment_type:
            "full-time", "contract", "part-time", "internship", null.
            Always explicitly stated. Critical for must_exclude: ["Contract"].

        integrity_score:
            0.0 to 1.0. Uses a deterministic rubric (documented in the prompt)
            so two LLMs given the same input return the same score, not vibes.

        source_url:
            Passed in from the scraper and echoed back. Enables deduplication
            at the extraction stage without re-joining on title+company (fragile).

    Generated by: nlp_engine.extract_jobs_from_text()
    Consumed by:  matcher.py (enhanced scoring), database.py, integrations/
    """

    # ── Identity ──────────────────────────────────────────────────────────────
    title:           str             = Field(..., description="Job title exactly as written.")
    company:         str             = Field(..., description="Company name exactly as written.")
    source_url:      Optional[str]   = Field(default=None, description="URL passed in from scraper.")
    seniority_level: Optional[str]   = Field(
        default=None,
        description="Allowed values: Staff, Principal, Senior, Mid, Junior, Lead, null. Level codes like L5 or IC5 are company-specific → return null."
    )
    employment_type: Optional[str]   = Field(
        default=None,
        description="Allowed values: full-time, contract, part-time, internship, null. Contract-to-hire is contract, not full-time."
    )

    # ── Compensation ──────────────────────────────────────────────────────────
    salary_min: Optional[int]   = Field(default=None, description="Lower bound in integers. null if not stated.")
    salary_max: Optional[int]   = Field(default=None, description="Upper bound in integers. null if not stated.")
    currency:   Optional[str]   = Field(
        default=None,
        description="ISO 4217 code. Default USD when $ symbol present and no country context contradicts it."
    )

    # ── Location / Remote ─────────────────────────────────────────────────────
    remote_region: Optional[str] = Field(
        default=None,
        description=(
            "GLOBAL: explicitly says worldwide/anywhere/all countries. "
            "US: says remote but requires US residency. "
            "EU / CA: specifies that region explicitly. "
            "CONFLICT: metadata contradicts body text. "
            "null: on-site or not stated."
        )
    )
    is_hybrid: bool = Field(
        default=False,
        description="True only if the post explicitly mentions hybrid arrangement."
    )
    location_strictness: Optional[str] = Field(
        default=None,
        description=(
            "How accessible this job is for the user in Lima, Peru. "
            "Strict: requires US presence/citizenship — user cannot apply. "
            "Flexible: timezone/hours-based but contractors may qualify. "
            "Match: global, LATAM, or no restriction — user is a fit."
        )
    )
    location_notes: Optional[str] = Field(
        default=None,
        description=(
            "1-2 sentences explaining why this job works or conflicts for "
            "someone in Lima, Peru (EST/UTC-5). Quote the relevant phrase."
        )
    )

    # ── Tech Stack ────────────────────────────────────────────────────────────
    required_tech:  list[str] = Field(
        default_factory=list,
        description="Technologies explicitly marked as required. Never infer."
    )
    preferred_tech: list[str] = Field(
        default_factory=list,
        description="Technologies explicitly marked as preferred/nice-to-have. Never infer."
    )

    # ── Experience ────────────────────────────────────────────────────────────
    experience_min_years: Optional[int] = Field(
        default=None,
        description="Lower bound. '3-5 years' → 3. null if not stated."
    )
    experience_max_years: Optional[int] = Field(
        default=None,
        description="Upper bound. '3-5 years' → 5. null if not stated."
    )

    # ── Personalization ───────────────────────────────────────────────────────
    cv_match_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description=(
            "How well the job's tech stack matches the user's core skills. "
            "1.0 = perfect overlap. 0.0 = zero overlap. Always computed."
        )
    )

    # ── Quality Signal ────────────────────────────────────────────────────────
    integrity_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description=(
            "Additive score 0.0-1.0. Add +0.2 for each: salary stated as number, "
            "tech stack has 1+ items, experience stated, location unambiguous (Case A-D), "
            "company+title both present."
        )
    )

    @field_validator("title", "company", mode="before")
    @classmethod
    def strip_and_require_nonempty(cls, v):
        """Strips whitespace and rejects empty or whitespace-only strings."""
        if v is None:
            raise ValueError("field is required and cannot be null")
        cleaned = str(v).strip()
        if not cleaned:
            raise ValueError("field cannot be empty or whitespace-only")
        return cleaned

    @field_validator("salary_min", "salary_max", mode="before")
    @classmethod
    def coerce_salary(cls, v):
        """Coerces string salary values to int, rejects non-numeric."""
        if v is None:
            return None
        if isinstance(v, (int, float)):
            return int(v)
        if isinstance(v, str):
            cleaned = v.strip().replace(",", "").replace("$", "").replace("k", "000").lower()
            try:
                return int(float(cleaned))
            except ValueError:
                return None
        return None

    @field_validator("location_strictness", mode="before")
    @classmethod
    def normalize_location_strictness(cls, v):
        if v is None:
            return None
        allowed = {"Strict", "Flexible", "Match"}
        for a in allowed:
            if str(v).strip().lower() == a.lower():
                return a
        return None

    @field_validator("cv_match_score", mode="before")
    @classmethod
    def clamp_cv_match(cls, v):
        try:
            return max(0.0, min(1.0, float(v)))
        except (TypeError, ValueError):
            return 0.0

    @field_validator("remote_region", mode="before")
    @classmethod
    def normalize_remote_region(cls, v):
        """Normalises to uppercase allowed values."""
        if v is None:
            return None
        allowed = {"GLOBAL", "US", "EU", "CA", "CONFLICT"}
        upper = str(v).strip().upper()
        return upper if upper in allowed else None

    @field_validator("employment_type", mode="before")
    @classmethod
    def normalize_employment_type(cls, v):
        """Normalises to lowercase allowed values."""
        if v is None:
            return None
        allowed = {"full-time", "contract", "part-time", "internship"}
        lower = str(v).strip().lower()
        return lower if lower in allowed else None

    @field_validator("integrity_score", mode="before")
    @classmethod
    def clamp_integrity(cls, v):
        """Clamps to [0.0, 1.0] in case LLM returns out-of-range value."""
        try:
            return max(0.0, min(1.0, float(v)))
        except (TypeError, ValueError):
            return 0.0


class ExtractionResult(BaseModel):
    """
    Wrapper for the full output of extract_jobs_from_text().
    A list of ExtractedJob objects. Empty list signals garbage/duplicate input.

    Generated by: nlp_engine.extract_jobs_from_text()
    """
    jobs: list[ExtractedJob] = Field(default_factory=list)

    @model_validator(mode="before")
    @classmethod
    def skip_invalid_jobs(cls, data):
        """
        Validates each job entry individually and silently drops any that fail
        (missing/empty title or company). Valid entries are never affected.
        """
        if not isinstance(data, dict) or "jobs" not in data:
            return data
        valid = []
        for raw in data.get("jobs") or []:
            try:
                ExtractedJob.model_validate(raw)
                valid.append(raw)
            except Exception:
                pass
        data["jobs"] = valid
        return data
